# spring config
spring:
  # Spring的自动扫描包
  packageScan: ['komics']
  # 如果要扩展spring的配置, 通过这里指定配置类
  configurationClasses: []
  dispatcherServletMapping: "/"
---
# 数据源配置,支持多个数据源
datasource:
  # 阿里巴巴的 druid data source
  -
    name: "default-datasource"
    class: "com.alibaba.druid.pool.DruidDataSource"
    url: "jdbc:mysql://localhost:3306/decor_new"
    username: 'root'
    password: 'Qwer!234'
    minIdle: 5
    initialSize: 10
    maxActive: 100
